### ISSUE TITLE
Network colouring based on GeneLists

### ISSUE THREAD

**Issue by irusri** [PlantGenIE/PlantGenIE#88]

**Comment by irusri** [comment]
I updated network colouring feature on https://beta.plantgenie.org/exNet. If you are happy I will update into the main site. Thanks

**Comment by irusri** [comment]
Here I updated screencast http://recordit.co/ZDD5Swwljt

**Comment by irusri** [comment]
updated files sidebar.js and init.js

**Comment by natstreet** [comment]
This is great. Would it be possible to have the controls in the area under the network graph rather than inside of it? It also might work better if this could use a drop down list of gene lists. How you have it at the moment works fine if a user has only a small number of lists but will not work, or will work less well, if they have e.g. 10 lists and are using a small screen.

We should also remember that we want to have a second set of lists available for each network that contain ready available lists of gene in network modules (e.g. from InfoMap).

Great that this is working!

**Comment by irusri** [comment]
I just added Toggle button to show/ hide visibility of color picker list. It looks like this screencast : http://g.recordit.co/YNtWukwORp.gif

**Comment by irusri** [comment]
Available on main site as well
